defaults:
  - _self_
  - dataset: PoolData
  - model: cnn
  - hydra: default.yaml

# Path for saving model weights
path:
  output_path: './weights'

# Hyperparameters
hyp:
  batch_size: 32
  num_epochs: 100
  learning_rate: 1e-3
  weight_decay: 1e-4

device:
  gpu: 0  # GPU ID
  num_workers: 8  # Number of workers for data loading, multiprocessing enabled if > 0

task: "classification"
log: False
plots: true