#!/usr/bin/env python

import rospy
from pose_estimator.main import PoseSequence


def main():
    rospy.init_node('pose_estimator')
    PoseSequence()

    try:
        rospy.spin()
    except KeyboardInterrupt:
        pass


if __name__ == '__main__':
    main()
